/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ejemploudp;

import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author roafi
 */
public class Cliente extends javax.swing.JFrame {
    private Menu menu;
    private boolean activo; //Para verificar que si se cierr ala ventan ael hilo se cerrara
    private HiloCliente hilo;
    /**
     * Creates new form Cliente
     */
    public Cliente(Menu menu) {
        initComponents();
        this.menu=menu;
        activo=true;
        Toolkit tk=Toolkit.getDefaultToolkit();
        Dimension d=tk.getScreenSize();
        setTitle("Cliente UDP");
        setSize(415,330);
        setLocation((d.width-getSize().width)/2,(d.height-getSize().height)/2);
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        hilo=new HiloCliente(this);
        hilo.start();
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblIP = new javax.swing.JLabel();
        txtIP = new javax.swing.JTextField();
        lblPuerto = new javax.swing.JLabel();
        txtPuerto = new javax.swing.JTextField();
        scrMensajes = new javax.swing.JScrollPane();
        txtMensajes = new javax.swing.JTextArea();
        lblA = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        lblIP.setText("IP SERVIDOR");
        getContentPane().add(lblIP);
        lblIP.setBounds(10, 20, 130, 20);

        txtIP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIPActionPerformed(evt);
            }
        });
        getContentPane().add(txtIP);
        txtIP.setBounds(90, 20, 120, 20);

        lblPuerto.setText("PUERTO");
        getContentPane().add(lblPuerto);
        lblPuerto.setBounds(220, 20, 50, 20);
        getContentPane().add(txtPuerto);
        txtPuerto.setBounds(270, 20, 120, 20);

        txtMensajes.setEditable(false);
        txtMensajes.setColumns(20);
        txtMensajes.setRows(5);
        scrMensajes.setViewportView(txtMensajes);

        getContentPane().add(scrMensajes);
        scrMensajes.setBounds(10, 50, 380, 150);

        lblA.setText("NOMBRE:");
        getContentPane().add(lblA);
        lblA.setBounds(20, 220, 140, 20);
        getContentPane().add(txtNombre);
        txtNombre.setBounds(110, 220, 280, 20);

        btnEnviar.setText("ENVIAR");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar);
        btnEnviar.setBounds(87, 260, 90, 23);

        btnCerrar.setText("CERRAR");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });
        getContentPane().add(btnCerrar);
        btnCerrar.setBounds(213, 260, 90, 23);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIPActionPerformed

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
       menu.setVisible(true);
       activo=false;
       hilo.notificar();
       this.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        menu.setVisible(true);
        activo=false;
        hilo.notificar();
    }//GEN-LAST:event_formWindowClosing

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        if (txtIP.getText().equals("")||txtPuerto.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Completa los campos de IP y PUERTO!!");
        else if (txtNombre.getText().equals(""))
            JOptionPane.showMessageDialog(null, "Introduce el nombre a enviar");
        else
            hilo.notificar();
    }//GEN-LAST:event_btnEnviarActionPerformed
    public String getIP()
    {
        return txtIP.getText().trim(); //.trim quita los espacios del incio y el fin
    }
    public String getPuerto()
    {
        return txtPuerto.getText().trim();
    }
    
    /**
     * @param args the command line arguments
     */
    public void setMensaje(String msg)
    {
        txtMensajes.setText(msg);
    }
    
    public String getMensaje()
    {
        return txtMensajes.getText();
    }
    
    public boolean getActivo()
    {
        return activo;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel lblA;
    private javax.swing.JLabel lblIP;
    private javax.swing.JLabel lblPuerto;
    private javax.swing.JScrollPane scrMensajes;
    private javax.swing.JTextField txtIP;
    private javax.swing.JTextArea txtMensajes;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPuerto;
    // End of variables declaration//GEN-END:variables
}
